[project]
name = "reinforcementlearning-dqn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "gymnasium[box2d,other]>=1.2.2",
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
    "optuna>=4.6.0",
    "requests>=2.32.5",
    "stable-baselines3[extra]>=2.7.1",
    "swig>=4.4.0",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.23.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128Copied!"


[tool.setuptools.packages.find]
where = ["."]  # Procura na raiz
include = ["core*"]  # Inclui APENAS o código real
namespaces = false # Opcional: evita criar namespaces implícitos se não precisar
